### ISSUE TITLE
Sample code for kindle version

### ISSUE THREAD

**Issue by sligo-kk9** [objcio/functional-swift#100]
The version of the book which I downloaded from Amazon on 08/11/2015 does not include any sample code.  In particular, I am looking for the Spreadsheet project.  Is there a link where the sample code can be downloaded?

**Comment by david-mcqueen** [comment]
To jump on the back of this comment; I also think it would be beneficial to have an up to date download of the complete sample code. I am working through the printed version of the book, and I am finding it increasingly frustrating that every time I pick the book up the sample code doesn't work in playground. I appreciate that Swift is changing as it gets developed, but I feel that if there was downloadable source code it would make debugging errors much easier. I wouldn't be thinking "Have I made a type o", "have I missed something", "is there a function that wasn't declared in the book that is necessary for this bit of code to work", or "is this something that has broken with a newer version of Swift", all of which are seemingly possible, and with nothing to cross reference they are all quite probable.

**Comment by floriankugler** [comment]
@sligo-kk9 @david-mcqueen Yeah, we agree that this is not a good situation.

We'll change this with the upcoming update for Swift 2. We'll make all the source code publicly available via GitHub, so that everyone who buys the book (through whatever channel) has easy access to it.
