### ISSUE TITLE
Applicative Functor

### ISSUE THREAD

**Issue by onmyway133** [objcio/functional-swift#101]
I'm reading chapter `Functor, Applicative Functor and Monads`, section `Applicative Functor`

There is an example about `Region`

```
> Applicative functors have been lurking in the background throughout this book. For example, the Region struct defined above is also an applicative functor:

func pure<A>(value: A) -> Region<A> {
    return Region { pos in value }
}

func <*><A,B>(regionF: Region<A -> B>, 
              regionX: Region<A>) -> Region<B> {
              
    return Region { pos in regionF.value(pos)(regionX.value(pos)) }
}
```

Can you explain more about this `Region { pos in regionF.value(pos)(regionX.value(pos)) }` ? What is the `value` inside `regionF`? Can you give an example?

**Comment by floriankugler** [comment]
@onmyway133 Look a few paragraphs above. There the struct `Region<T>` is introduced which has the `value` property.
