### ISSUE TITLE
Type of expression Ambiguous

### ISSUE THREAD

**Issue by SammyLedgard** [objcio/functional-swift#102]
Working through your Trie example and getting an error on the elements function

````Swift
func elements<T: Hashable>(trie: Trie<T>) -> [[T]]
{
    var result: [[T]] = trie.isElem ? [[]] : []

    for (key, value) in trie.children {
        result += elements(value).map {xs in [key] + xs} // error on this line
    }
    return result
}
````

Error is __"Type of expression is ambiguous without more context"__
I am using Xcode 7 with Swift 2

Any suggestions or hints appreciated

**Comment by floriankugler** [comment]
We've rewritten this to use an extension on `Trie`. The update will be out very soon and the code will be up in this repo. Thanks for the feedback!
