### ISSUE TITLE
Error in CoreImage Wrapper colorOverlay function

### ISSUE THREAD

**Issue by karthikgs7** [objcio/functional-swift#105]
<img width="935" alt="screen shot 2015-10-03 at 1 24 25 pm" src="https://cloud.githubusercontent.com/assets/4941940/10261980/3c3bda44-69d2-11e5-9920-4f64134b5f71.png">

When, I call the colorGenerator and compositeSourceOver, separately, it works fine. I got error only, when I calling colorOverlay function.

**Comment by pauluhn** [comment]
Also getting an error...
![screen shot 2015-10-16 at 10 04 00 am](https://cloud.githubusercontent.com/assets/6515165/10545243/4ed21e82-73ed-11e5-94b4-dd0faf8915d8.png)

Based on https://github.com/objcio/functional-programming-in-swift/issues/77, I switched to a CIColor as the input color but still getting error.
![screen shot 2015-10-16 at 10 09 34 am](https://cloud.githubusercontent.com/assets/6515165/10545376/07ba7dcc-73ee-11e5-8a35-0a466ea3e90c.png)

I notice that in https://github.com/objcio/issue-16-functional-apis/blob/master/FunctionalCoreImage/CoreImage.swift, you unwrap the CIColor but when I try to, it says its a non-optional.

**Comment by afterfriday** [comment]
To fix this problem need set size for output image in CIConstantColorGenerator filter, try this function

func colorGenerator(color: NSColor) -> Filter {
    return { image in
        guard let c = CIColor(color: color) else { fatalError() }
        let parameters = [kCIInputColorKey: c]
        guard let filter = CIFilter(name: "CIConstantColorGenerator", withInputParameters: parameters) else { fatalError() }
        guard let outputImage = filter.outputImage?.imageByCroppingToRect(image.extent) else { fatalError() }
        return outputImage
    }
}

**Comment by trozware** [comment]
afterfriday's fix worked for me - thanks very much.
This is really just applying the same crop as used in compositeSourceOverlay.
I still had a problem due to my own typo in the filter name, so that is worth checking if things are going weird.

With the CIColor un-wrapping, if you are using an iOS playground with UIColor, the CIColor initialiser does not return an optional. If you are using an NSColor, it does.

**Comment by chriseidhof** [comment]
Thanks for all the comments everyone. Unfortunately, we can't do much about it until Apple fixes this =).
