### ISSUE TITLE
Incorrect definition of MayorResult

### ISSUE THREAD

**Issue by TicTocCroc** [objcio/functional-swift#109]
In the *Adding Generics* section of the *Enumerations* chapter, the `MayorResult` enumeration is defined with an `Int` associated value, but the value of a mayor is a string. This definition appears to be incorrect, and the mistake is exacerbated by the discussion in the preceding paragraphs.

**Comment by chriseidhof** [comment]
Yes, thanks for reporting. We'll fix this!
