### ISSUE TITLE
Why GeneratorType have map method ？

### ISSUE THREAD

**Issue by cache0928** [objcio/functional-swift#111]
![2015-12-31 at 12 18](https://cloud.githubusercontent.com/assets/7350995/12061102/abdda1e4-afb8-11e5-8b2d-11c85f37ec38.png)

**Comment by cache0928** [comment]
I dont know the meaning of "generator = g.map(anyGenerator)"
I cant run this code in playground

**Comment by justadreamer** [comment]
It's defined elsewhere as an extension on GeneratorType (f.e. see parsing.swift)

```
extension GeneratorType {
    mutating func map<B>(transform: Element -> B) -> AnyGenerator<B> {
        return anyGenerator {
            self.next().map(transform)
        }
    }
}

```
