### ISSUE TITLE
rename CollectionType.decompose into CollectionType.decomposed

### ISSUE THREAD

**Issue by justadreamer** [objcio/functional-swift#112]
Since this is a non-mutating property (implicit non-mutating method call) - should be named ending in 'ed'.  The verb is for mutating methods.  This is also according a draft style guide: https://swift.org/documentation/api-design-guidelines.html#be-grammatical.
Also could be named as a noun, f.e: `decomposition`.  
What do you think?

**Comment by chriseidhof** [comment]
Completely agree, will be fixed in the next edition.
