### ISSUE TITLE
Book revision in the book.

### ISSUE THREAD

**Issue by Handfast** [objcio/functional-swift#114]
It would be great to have a date or some type of version information of the book inside it, since iBooks doesn't give any sign of created date or the like in the interface. - Thanks for great writing!

**Comment by chriseidhof** [comment]
I think that's a good idea. We might have some support for that already.
@floriankugler could you chime in on this?

On Tue, Mar 8, 2016 at 9:55 PM, Handfast <notifications@github.com> wrote:

> It would be great to have a date or some type of version information of
> the book inside it, since iBooks doesn't give any sign of created date or
> the like in the interface. - Thanks for great writing!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/objcio/functional-swift/issues/114>.
>



-- 
Chris Eidhof

**Comment by floriankugler** [comment]
Yes, we do have this in the new version.
