### ISSUE TITLE
Ambiguous Issue

### ISSUE THREAD

**Issue by donnycode** [objcio/functional-swift#116]
Xcode 7.2.1
Swift 2.1.1

Ambiguous issue

func check2<A: Arbitrary>(message: String, _ property: A -> Bool) -> ()

![screen shot 2016-04-01 at 12 42 06 pm](https://cloud.githubusercontent.com/assets/11582508/14218135/2eb7b42e-f807-11e5-97e8-1669ffc62a70.png)

**Comment by chriseidhof** [comment]
Thanks for letting us know!

In the text, it explains why this doesn't work. In the paragraphs after that, we show how to implement a different variant that does work:

    func check<X: Arbitrary>(message: String, _ property: [X] -> Bool) -> () {
