### ISSUE TITLE
generate function in Wrapping Core Image chapter crashes

### ISSUE THREAD

**Issue by hugofalkman** [objcio/functional-swift#129]
filter.outputImage crashes with console message from CGContext saying invalid context 0x0

// Playground: Test generate

import UIKit

let color = UIColor.red.withAlphaComponent(0.2)
let parameters = [kCIInputColorKey: CIColor(cgColor: color.cgColor)]
let filter = CIFilter(name: "CIConstantColorGenerator", withInputParameters: parameters)!
filter.outputImage

**Comment by chriseidhof** [comment]
Hi @hugofalkman, I remember we had this problem with old versions UIKit. Could you try on a recent version or on the Mac? It might also be a new problem, not sure!

**Comment by hugofalkman** [comment]
Am on latest Xcode 8.2.1 so am sure it's a new problem. Just copy my code into a fresh Xcode playground to reproduce.

**Comment by hugofalkman** [comment]
The following solves the bug:

The cropping method isn't really cropping, it adjusts to the size of the to: parameter whether it's larger or smaller than the input image.

CIConstantColorGenerator generates an image with size 0x0, so you need to apply the cropping method before returning it as output of the generate function. That means it needs to use the input image just like the other functions. The following generate function works without crashing in the Xcode 8.2.1 playground:

`func generate(color: UIColor) -> Filter {`
`    return { image in`
`        let parameters = [kCIInputColorKey: CIColor(cgColor: color.cgColor)]`
`        guard let filter = CIFilter(name: "CIConstantColorGenerator",`
`                                    withInputParameters: parameters)`
`            else { fatalError() }`
`        guard let outputImage = filter.outputImage`
`            else { fatalError() }`
`        return outputImage.cropping(to: image.extent)`
`    }`
`}`


Btw the blur function returns an image larger than the input image, so it also needs cropping in the return statement. Once you have added cropping to all the other functions, cropping is no longer needed in the overlay function.

Also to avoid all the "failed to obtain sandbox extension" warning messages I added the following to the Xcode 8.2.1 playground:
URLCache.shared = URLCache(memoryCapacity: 0, diskCapacity: 0, diskPath: nil)

[TheFilterType.playground.zip](https://github.com/objcio/functional-swift/files/832617/TheFilterType.playground.zip)

**Comment by chriseidhof** [comment]
Thanks a lot @hugofalkman ! 

I'm going to leave this open until we have time to do a proper update of the book. That will also help other people stumbling over this issue.

**Comment by hugofalkman** [comment]
This issue was closed, but I don't see an updated version of the book on Gumroad.

**Comment by chriseidhof** [comment]
No, we're working on it =)
