### ISSUE TITLE
Infinite loop in FileLinesIterator

### ISSUE THREAD

**Issue by belous** [objcio/functional-swift#130]
Hi!

This is `FileLinesIterator` from Chapter 11 Iterators and Sequences:

```
struct FileLinesIterator: IteratorProtocol {
    let lines: [String]
    var currentLine: Int = 0

    init(filename: String) throws {
        let contents: String = try String(contentsOfFile: filename)
        lines = contents.components(separatedBy: .newlines)
    }

    mutating func next() -> String? {
        guard currentLine < lines.endIndex else { return nil }
        return lines[currentLine]
    }
}
```
The problem that `next()` function falls into an infinite loop because there is no any incrementation of the `currentLine` variable.

**Comment by chriseidhof** [comment]
Yes! We fixed this in our book repository, thanks a lot. It should have a `defer { currentLine += 1 }` in between the two statements, like this:

```
    mutating func next() -> String? {
        guard currentLine < lines.endIndex else { return nil }
        defer { currentLine += 1 }
        return lines[currentLine]
    }
```

**Comment by tkrajacic** [comment]
Wouldn't it make the code more readable in this case to not use `defer`.

What I mean is that the last line `return lines[currentLine]` is telling a wrong story. the entire method is there to actually return `return lines[currentLine + 1]` hence the `next()` name.

I'd argue that using defer here is misleading and obscures the intent. (Of course your implementation is correct though and absolutely does what it is supposed to – no arguing there)

I just remember reading some article somewhere of when not to use `defer` and this seems very much like a prime example. (There is only a single path out of the function for starters)

**Comment by chriseidhof** [comment]
Good point, we'll consider that! For such a simple example I think it's okay, but we'll take it into account for the next update, thank you!
