### ISSUE TITLE
error while calling  colorGenerator

### ISSUE THREAD

**Issue by qwind365** [objcio/functional-swift#131]
```
func colorGenerator(color:UIColor) -> Filter {
    return {
        image in
        
        let params = [kCIInputColorKey:CIColor.init(red: 1, green: 0, blue: 0, alpha: 0.2)] as [String:Any]
        guard let filter = CIFilter.init(name: "CIConstantColorGenerator", withInputParameters: params) else {
            fatalError()
        }
        
        guard let outputImage = filter.outputImage else     {
            fatalError()
        }
        return outputImage.cropping(to: image.extent)
    }
}
```

who can tell me how to fix it? thank you !

**Comment by chriseidhof** [comment]
Hm, on which platform are you trying? What is the error you're getting?

**Comment by qwind365** [comment]
@chriseidhof   I  run it on xcode 8.3.2 playground.

error: Playground execution aborted: error: Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).
The process has been left at the point where it was interrupted, use "thread return -x" to return to the state before expression evaluation.

**Comment by swiftxy** [comment]
I  have the same problem

**Comment by chriseidhof** [comment]
Is this an iOS or Mac playground? Switching between the two might help! Or could you post the complete playground?

**Comment by high5Fly** [comment]
For me the problem came from how I pass the color. 

I used first UIColor - color.ciColor, with this was crashing. Then I switch to this from a comment here "[kCIInputColorKey:  CIColor(cgColor: color.cgColor)]" and it worked.

I am on XCode 9.2
