### ISSUE TITLE
Workaround for qsort intermediate let

### ISSUE THREAD

**Issue by alessandro-martin** [objcio/functional-swift#134]
As stated in the book, because of https://bugs.swift.org/browse/SR-1914, we can't simply do:
`return qsort(lesser) + [pivot] + qsort(greater)`
but what about:
`return qsort(lesser) + Array(arrayLiteral: pivot) + qsort(greater)`
and getting rid of the intermediate let?

**Comment by chriseidhof** [comment]
That would work, but it's also pretty ugly! (Not your mistake, Swift's mistake). We'll revisit the example for the next update!
