### ISSUE TITLE
sample trie (Chapter 9)

### ISSUE THREAD

**Issue by sstadelman** [objcio/functional-swift#22]
I feel really dumb asking this, but could you provide a sample trie for the Chapter 9 discussion, similar to the Trees that were shared "by hand"?  

e.g.

```
let leaf: Tree<Int> = Tree.Leaf
let five: Tree<Int> = Tree.Node(Box(leaf), 5, Box(leaf))

let trie1 = Trie.Make(true, <some recursive dictionary?>)
```

This is an awesome chapter, but trying to wrap my head around inserting a recursive associative value (?) in an collection of enum cases... is blowing my mind.

help?

**Comment by hatebyte** [comment]
I finally understood that order establish an end to a "word", the trie's children must have with at least one trie that has `isElem` set to `true`. So it does make sense that the empty function returns a trie whos `isElem` is `true`. Then the single function should just a trie whos children are empty as well.

    func empty<T : Hashable>()->Trie<T> {
        return Trie(isElem:true, children:[T:Trie<T>]())
    }

    func single<T : Hashable>(t:T)->Trie<T> {
        return Trie(isElem:false, children:[t:empty()])
    }  

This was a great chapter and with the help from above I elaborated on the example and made a function to add an array to an existing trie while maintaining its child relationships.  Thanks for the help guys and great book @wouter-swierstra.

    func create<T: Hashable>(t:[T])->Trie<T> {
        let trie = t.reverse().reduce(empty()) { tr, next in
            return Trie.Make(false, children:[next:tr])
        }
        return trie
    }

    func addTo<T: Hashable>(t:[T], trie:Trie<T>)->Trie<T> {
        if let (head, tail) = t.decompose {
            var children                = trie.children
            var trieToReturn:Trie<T>!
            if let subTrie = children[head] {
                if tail.count > 0 {
                    // keep drilling down till you hit the last of the array 
                    // or have to create the new trie
                    trieToReturn = addTo(tail, subTrie)
                } else {
                    // its the last in the array, 
                    // create trie with lastElem true and add it to the children
                    trieToReturn = Trie.Make(true, children:subTrie.children)
                }
            } else {
                // head is not a part of the trie,
                // create its own and to tri children
                trieToReturn = create(tail)
            }
            // return trie with adjusted children and copy lastElem
            children[head] = trieToReturn
            return Trie.Make(trie.isElem, children:children)
        } else {
            return trie
        }
    }

    func wordToStringArray(word:String)->[String] {
        return Array(word).map { c in String(c) }
    }

    let beard               = wordToStringArray("beard")
    let bear                = wordToStringArray("bear")
    let beer                = wordToStringArray("beer")
    let beet                = wordToStringArray("beet")
    let beef                = wordToStringArray("beef")
    let be                  = wordToStringArray("be")
    let golf                = wordToStringArray("golf")

    var completionList:Trie<String>!
    completionList          = create(be)
    completionList          = addTo(beard, completionList)
    completionList          = addTo(bear, completionList)
    completionList          = addTo(be, completionList)
    completionList          = addTo(beer, completionList)
    completionList          = addTo(beef, completionList)
    elements(completionList)

    let test                = wordToStringArray("b")
    let ac                  = autoComplete(test, completionList)//.map { c in c.reduce("") { f,n in f + n } }

**Comment by wouter-swierstra** [comment]
Thanks @hatebyte! I recently added a very similar function to this chapter (should be in the next update we release). I've had some issues with the addTo functions triggering Swift bugs in the past; I'll check whether this is fixed in the latest version. Ideally, I'd like to include a small demo/playground with the chapter to help visualise how tries are built and searched.
