### ISSUE TITLE
GeneratorOf vs. GeneratorType

### ISSUE THREAD

**Issue by ole** [objcio/functional-swift#89]
Question about the `+` function to append one `GeneratorOf`s to another:

![img_0339](https://cloud.githubusercontent.com/assets/5010/7429108/2846c526-effc-11e4-9cb0-3922f0087c4e.PNG)

Is there a specific reason why you used `GeneratorOf` for the arguments here? Wouldn't it be better/more generic to use `GeneratorType`? Like this:

    func +<G, E where G : GeneratorType, G.Element == E>(var first: G, var second: G) -> GeneratorOf<E> {
        return GeneratorOf {
            first.next() ?? second.next()
        }
    }

**Comment by chriseidhof** [comment]
Yes, it's more generic... but I think the other one is a bit simpler to understand. I'll leave this open so we can ponder on it a bit more.

**Comment by chriseidhof** [comment]
Will be fixed in the next update.
