### ISSUE TITLE
Sample code output is missing in EPUB version of the book

### ISSUE THREAD

**Issue by ole** [objcio/functional-swift#90]
The EPUB version of the book (from 2015-04-22) does not include the output from sample code snippets. See this as an example: the highlighted code should be followed by its output (which is present in the PDF version). As far as I can tell, this error(?) goes through the entire book, not just in some chapters.

![img_0340](https://cloud.githubusercontent.com/assets/5010/7429147/b4114bc6-effc-11e4-96b9-d326dcec0e2b.PNG)

For comparison, a screenshot from the PDF:

![screen shot 2015-05-01 at 12 22 54](https://cloud.githubusercontent.com/assets/5010/7429154/ce5bff1c-effc-11e4-94f6-a8a198663196.png)

**Comment by floriankugler** [comment]
Will be fixed in upcoming update.
