### ISSUE TITLE
Value of Immutability: Referential transparency?

### ISSUE THREAD

**Issue by jeremy-w** [objcio/functional-swift#98]
This chapter defines referential transparency as "functions that compute the same output for equal inputs". I worry this might be misleading, since it might lead the reader to think that this function is referentially transparent:

```swift
func writeRandomDatatoHomeDirectory(confirmed: Bool) -> Bool {
    guard confirmed else { return false }
    /* write the address of confirmed to ~/confirmed.txt */ 
    return true
}
```

Including some remark about "without any observable side effects" might be enough to correct this. The heart of referential transparency in my eyes is being able to "look through" all references by substituting the definition in-place for the reference (AKA in-lining the referent) without changing the observed behavior of the program.

**Comment by chriseidhof** [comment]
Good point! We will look into this for the next update =). Thanks a lot!
